### ISSUE TITLE
appCom.dll Question

### ISSUE THREAD

**Issue by netphreak** [AdvancedHacker101/C-Sharp-R.A.T-Client#7]
Hello, First want to say great projects (Client and Server) this will help tremendously with a current project for work.
My question is do you or can you post the source code for the appCom.dll ? or 
show me how to get it.

Thank you very much and again great projects.

**Comment by AdvancedHacker101** [comment]
Hi!
Thank you for taking a look at the project! :+1:   
Sorry for not posting the code for appCom.dll, i should have posted it, because this is an open source project.  
I think it's not worth creating a repo, so i created a gist for it which you can check out [here](https://gist.github.com/AdvancedHacker101/0ae8abb25610e1c6119d84304cd78b08).  
Thank you for your question, have a nice day!  
**Advanced Hacking 101**
